### ISSUE TITLE
Processing results to a server

### ISSUE THREAD

**Issue by volkerku** [MartinFk/VRQuestionnaireToolkit#15]
looks like a great tool. I'll give it a try.
is there a way to send the survey result data to a server instead of the local file system?

**Comment by MartinFk** [comment]
thank you very much for your interest in the VRQuestionnaireToolkit. 

This feature is on our ToDO list; however, it is unfortunately not supported at the moment. 

You can retrieve the data (questionId, response etc.) in the .../Assets/Questionnaires/Scripts/Export/ExportToCSV.cs script line 252 from the _csvRows array, after the user presses the submit button. So, you should be able to further process it to a server.

 I hope this help.

**Comment by MartinFk** [comment]
Integrated in V1.4.
