### ISSUE TITLE
DOI Link is no longer working.

### ISSUE THREAD

**Issue by DerLeole** [MartinFk/VRQuestionnaireToolkit#27]
I know this might not be the right place, but I found your paper and wanted to cite it and found out that the doi link: https://doi.org/10.1145/3379350.3416188 doesn't seem to work anymore.

I hope this can be fixed.

**Comment by MartinFk** [comment]
Thank you very much for pointing this out! 

I reported the invalid DOI. I hope they fix it as soon as possible. 

You can find the paper under: https://dl.acm.org/doi/abs/10.1145/3379350.3416188

**Comment by MartinFk** [comment]
Fixed
