### ISSUE TITLE
imcompatible with Unity 2021?

### ISSUE THREAD

**Issue by xxxhhhyxy** [MartinFk/VRQuestionnaireToolkit#29]
I used Unity 2021.3.8f1 to open your project, then:

Assets\SteamVR\Editor\SteamVR_AutoEnableVR.cs(64,68): error CS0117: 'VREditor' does not contain a definition for 'GetVREnabledDevicesOnTargetGroup'
 help me, because I really want to use it!

**Comment by MartinFk** [comment]
Seems like a SteamVR issue. Just to double-check, did you enable (check) OpenVR in Unity3D? Which version are you using: Standalone or Integration?

**Comment by MartinFk** [comment]
I assume the issue got resolved.
